apiVersion: apps/v1
kind: Deployment
metadata:
  name: shubhrant
  labels:
    app: hello-world
    org: orange
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: shubhrant
        image: anandshbh/shubhrant:latest
        ports:
        - containerPort: 5000


